import { GoogleGenAI, Type } from "@google/genai";
import { createClient } from "@supabase/supabase-js";

export default async function handler(req: any, res: any) {
  // 1. Check method
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // 2. Check environment variables
  const supabaseUrl = process.env.SUPABASE_URL;
  const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;
  const geminiApiKey = process.env.API_KEY;

  if (!supabaseUrl || !supabaseAnonKey || !geminiApiKey) {
    return res.status(500).json({ 
      error: 'Environment variables are not configured on the server.',
      details: {
        supabaseUrl: supabaseUrl ? 'Set' : 'MISSING',
        supabaseAnonKey: supabaseAnonKey ? 'Set' : 'MISSING',
        geminiApiKey: geminiApiKey ? 'Set' : 'MISSING'
      }
    });
  }

  const { content, url } = req.body;

  if (!content) {
    return res.status(400).json({ error: 'Post content is required.' });
  }

  try {
    const supabase = createClient(supabaseUrl, supabaseAnonKey);
    const ai = new GoogleGenAI({ apiKey: geminiApiKey });
    
    const MARKETING_TOPICS = [
      'LinkedIn Ads', 'Meta Ads', 'Google Ads', 'TikTok Ads', 'Creative Testing',
      'Media Buying & Scaling', 'Funnels & CRO', 'Landing Pages', 'Lead Generation',
      'Email & Automation', 'Copywriting', 'Messaging & Positioning',
      'Personal Branding (LinkedIn)', 'Growth Strategy', 'AI in Marketing',
      'Analytics & Attribution', 'Agency & Client Management'
    ];

    const SYSTEM_PROMPT = `You are a professional marketing analyst. 
    Extract high-signal insights from LinkedIn posts. Remove all fluff and emojis.
    Classification: Strictly select ONE category from: ${MARKETING_TOPICS.join(', ')}.
    Response Format: Return raw JSON ONLY.`;

    // 3. AI Analysis with Gemini
    const result = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Analyze this LinkedIn post and provide high-signal marketing insights:
      URL: ${url || 'Not provided'}
      Content: ${content}`,
      config: {
        systemInstruction: SYSTEM_PROMPT,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            title: { type: Type.STRING },
            primary_topic: { type: Type.STRING },
            secondary_topics: { type: Type.ARRAY, items: { type: Type.STRING } },
            core_takeaway: { type: Type.STRING },
            summary: { type: Type.ARRAY, items: { type: Type.STRING } },
            key_insights: { type: Type.ARRAY, items: { type: Type.STRING } },
            original_text: { type: Type.STRING }
          },
          required: ['title', 'primary_topic', 'secondary_topics', 'core_takeaway', 'summary', 'key_insights', 'original_text'],
        }
      }
    });

    const textOutput = result.text;
    if (!textOutput) throw new Error("Gemini returned no text.");

    let analysis;
    try {
      const cleanJson = textOutput.replace(/```json/g, '').replace(/```/g, '').trim();
      analysis = JSON.parse(cleanJson);
    } catch (e) {
      console.error("JSON Parse Error. Raw output:", textOutput);
      throw new Error("AI output was not valid JSON.");
    }

    // 4. Save to Supabase (GLOBAL - no user_id mapping)
    // We keep all rich fields generated by Gemini for the UI to function correctly.
    const { data, error } = await supabase
      .from('marketing_posts')
      .insert([
        {
          url: url || null,
          title: analysis.title,
          primary_topic: analysis.primary_topic,
          secondary_topics: analysis.secondary_topics,
          core_takeaway: analysis.core_takeaway,
          summary: analysis.summary,
          key_insights: analysis.key_insights,
          original_text: analysis.original_text,
          // user_id is omitted or can be null to make this a global record
        }
      ])
      .select()
      .single();

    if (error) {
      console.error("Supabase error:", error);
      throw new Error(`Database storage failed: ${error.message}`);
    }

    return res.status(200).json(data);

  } catch (error: any) {
    console.error("Detailed Server Error:", error);
    return res.status(500).json({ 
      error: error.message || 'Server analysis failed'
    });
  }
}